//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.INew")]
    public interface INew {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INew/ReverseString", ReplyAction="http://tempuri.org/INew/ReverseStringResponse")]
        string ReverseString(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INew/ReverseString", ReplyAction="http://tempuri.org/INew/ReverseStringResponse")]
        System.Threading.Tasks.Task<string> ReverseStringAsync(string s);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewChannel : global::WcfClient.ServiceReference2.INew, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewClient : System.ServiceModel.ClientBase<global::WcfClient.ServiceReference2.INew>, global::WcfClient.ServiceReference2.INew {
        
        public NewClient() {
        }
        
        public NewClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ReverseString(string s) {
            return base.Channel.ReverseString(s);
        }
        
        public System.Threading.Tasks.Task<string> ReverseStringAsync(string s) {
            return base.Channel.ReverseStringAsync(s);
        }
    }
}
